### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [abbernie/tune#5]
Hello, 

I'm using tuna but today I saw some issues related with deprecation:

tuna-min.js:1 [Deprecation] DelayNode.delayTime.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
set @ tuna-min.js:1

tuna-min.js:1 [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.
set @ tuna-min.js:1

tuna-min.js:1 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
set @ tuna-min.js:1

tuna-min.js:1 [Deprecation] BiquadFilterNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
set @ tuna-min.js:1

tuna-min.js:1 [Deprecation] BiquadFilterNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
value @ tuna-min.js:1

tuna-min.js:1 [Deprecation] BiquadFilterNode.Q.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
value @ tuna-min.js:1

**Comment by taylorbf** [comment]
Hey @rodrigoprestesmachado ,

I think you are looking for [Tuna.js](https://github.com/Theodeus/tuna). This is Tune.js, a lib of different musical tunings in javascript. : )

**Comment by rodrigoprestesmachado** [comment]
I’m so sorry!

My mistake =(
